Memory driver multi  woker sync. ( memory config add `syncKey`, set …
hexindai/egg-cache pull request #12
Opened 2020-11-03 03:52 UTC by shudingbo

Memory driver multi  woker sync. ( memory config add `syncKey`, use for app.messenger action )
 > memory driver multi woker can't sync.

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

* memory driver

##### Description of change

使用内存驱动时，多个worker 之间没有同步.

2020-11-03 06:56 UTC, seekcx commented
首先感谢你的提交。

能告诉我你的使用场景吗？

我认为内存缓存同步没有必要，使用内存缓存的场景一般容许数据丢失，能根据持久存储来更新缓存，当 worker 线程被触发缓存行为之后再更新也是没有什么问题的。

2020-11-03 10:31 UTC, shudingbo commented
一个后台管理站点，缓存后台用户的各个子模块的权限信息（在用户退出或者30分钟未访问后缓存失效）。 使用内存比使用redis快了N倍（以前用的 redis）。

2020-11-03 10:52 UTC, shudingbo commented
在后台增加一个新模块，处理增加请求的那个 worker 的缓存更新了，但是其它worker没有更新缓存。 这就导致用户在使用时，如果正好是处理增加请求的worker，那用户可以看到模块，否则用户看不到增加的模块。

2020-11-04 03:27 UTC, seekcx requested changes
虽然我还是不太赞成这样做，但是在 egg 的模型下，多进程抹平差异是好事。

下面有些问题需要看一下。

2020-11-04 03:27 UTC, seekcx commented on app.js
> +  if (data.pid === pro.pid) {
这一块可以使用 egg 封装的进程通信来实现吗？

2020-11-04 03:27 UTC, seekcx commented on app.js
> +  if( defaultStore === 'memory' ) {
不用判断是否是 memory 驱动，如果使用 app.cache.store('memory') 的方式就没法同步了。

2020-11-04 03:27 UTC, seekcx commented on lib/cache.js
> +          argsT = args[0].args;
这里看起来是一个 breaking change，破坏了原来的参数。

2020-11-04 03:27 UTC, seekcx commented on lib/cache.js
> +          argsT = args[0].args;
这个 argsT 似乎没有用到

2020-11-04 08:59 UTC, shudingbo commented on app.js
> +  if (data.pid === pro.pid) {
egg提供的 IPC API 只有通知所有 worker的（包括了自己），所有的worker都会接收到这个消息。  这个判断用来处理，发送消息的worker不响应此消息，就不理（因为自己的已经设置过了）

2020-11-04 09:05 UTC, shudingbo commented on lib/cache.js
> +          argsT = args[0].args;
为了不增加新的接口来实现功能，原有的API(set, del)接口的第一个参数必然是string类型的，通过同步消息传过来的参数把所有数据封装作为一个对象。这几句就是来判断这个的。 应该不会影响原有的API。 您瞧一瞧

2020-11-04 09:06 UTC, shudingbo commented on lib/cache.js
> +          argsT = args[0].args;
下面的 调用应该是 argsT.  
```
return store(defaultStore).del(...argsT);  // 应该改为 argsT. 漏了  
```

2020-11-04 09:12 UTC, shudingbo commented on app.js
> +  if( defaultStore === 'memory' ) {
没有这种方式使用过，确实有这个问题。 这个判断是把增加的同步机制只限制在 memory store下。 因为 redis 是不需要这个的，如果不判断，那么 有N个 worker，redis的操作就会多 N-1次，这是不必要的IO。   
该怎么才能解决 `app.cache.store('memory')`这种方式的同步问题呢？您有没有什么好的想法

2020-11-04 11:36 UTC, shudingbo commented
重新更改了一下，cache 还原了， 在 store.js 做的更改，应该可以兼容几种使用方式了。 麻烦您看一看

2020-11-06 06:47 UTC, seekcx commented
> 重新更改了一下，cache 还原了， 在 store.js 做的更改，应该可以兼容几种使用方式了。 麻烦您看一看。
> 
> 为了把影响限制在 memory 模式下，几个地方都加了 memory的判断。

仔细看了一下实现，我不太能接受为了 memory 驱动做如此大的更改，建议自行封装完成同步。抱歉！

2020-11-06 06:47 UTC, closed without merging